name: "eb-deploy"
description: "deploy eb application"
inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ aws-region }}
