name: "eb-deploy"
description: "deploy eb application"
inputs:
  aws-access-key-id:
    description: ""
    required: true
    default: ""
  aws-secret-access-key:
    description: ""
    required: true
    default: ""
  aws-region:
    description: ""
    required: true
    default: ""
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-access-key-id }}
    - ${{ inputs.aws-secret-access-key }}
    - ${{ inputs.aws-region }}
